export const patient = {
  'first name': "impossible",
  'last name': "boi",
  'street address': "none",
  'zip': "1234",
  'birth date': "2021-06-09",
  'gender': "male",
  'phone': "123456789",
  'email': "something@something.com",
  'leave a message': "no",
  'relationship status': "yes",
  'filled out by': "template",
  'cancer type': "no cancer",
  'date of diagnosis': "2021-06-09",
  'diagnosis status': "yes",
  'doctor first name': "doctor",
  'doctor last name': "doctor",
  'doctor phone': "123456789",
  'walker, crutches, wheelchair': "no",
  'allergies':"no",
  'medical conditions':[],
  'living conditions explanation':"nope",
  'emergency contact first name': "you",
  'emergency contact last name': "the person reading this form",
  'emergency contact street address': "address",
  'emergency contact zip': "zip",
  'emergency contact phone': "1234",
  'emergency contact email': "something@something.com",
  'program selection':["not sure yet"],
  'religious beliefs':"yes",
  'open to prayer':"yes",
  'Financial assistance':"no",
  'applicant acknowledgement':true,
}

export const volunteer = {
  'first name': "volunteer",
  'last name': "21",
  'street address': "address",
  'zip': "1234",
  'birth date': "2021-06-09",
  'gender': "male",
  'phone': "123456789",
  'email': "something@something.com",
  'preferred point of contact': "phone",
  'best time to contact': "day",
  'relationship status': "none",
  'financial occupation':"beepboop",
  'employer':"self",
  'reference first name': "reference",
  'reference last name': "reference",
  'reference street address': "address",
  'reference zip': "1234",
  'reference phone': "123456789",
  'reference email': "somthing@something.com",
  'reference relationship to volunteer': "reference",
  'been a christian': "69 yrs",
  'rock attendance': "42 yrs",
  'rock campus': "all of them sir",
  'serving interests':["not sure yet"],
  'spiritual gifts test': "yes",
  'consider leader': "yes",
  'commit to 6 months of service': "yes",
  'past volunteer experience': "yes",
  'convicted of a felony': "no",
  // 'days available': {type: [String], required: true},
  'testimony of being saved':"im am fake i was born saved",
  'testimony of cancer':"im am fake i was born with cancer",
  'why volunteer question':"im am fake i was born to volunteer",
  'most difficult for volunteering question':"im am fake i was born with no difficult situations",
  'describe a difficult situation question':"im am fake i was born difficult",
  'healthy boundaries question': "im am fake i have no boundaries",
}
const template={patient,volunteer}
export default template
