const mongoose = require("mongoose")
const Schema = mongoose.Schema
const patientSchema = new Schema({
    isCheckedByAdmin: {type: Boolean, required: true},
    campus: {type: String},
    notes: {type: String},
    'patient ids paired with': {type: [String]},
    lastModified: {type: Date, required: true},
    'first name': {type: String, required: true},
    'last name': {type: String, required: true},
    'street address': {type: String, required: true},
    'zip': {type: String, required: true},
    'birth date': {type: String, required: true},
    'gender': {type: String, required: true},
    'phone': {type: String, required: true},
    'email': {type: String, required: true},
    'leave a message': {type: String, required: true},
    'relationship status': {type: String, required: true},
    'filled out by': {type: String, required: true},
    'filler first name': {type: String},
    'filler last name': {type: String},
    'filler phone': {type: String},
    'filler email': {type: String},
    'cancer type': {type: String, required: true},
    'date of diagnosis': {type: String, required: true},
    'diagnosis status': {type: String, required: true},
    'doctor first name': {type: String, required: true},
    'doctor last name': {type: String, required: true},
    'doctor phone': {type: String, required: true},
    'walker, crutches, wheelchair': {type: String, required: true},
    'allergies':{type:String},
    'medical conditions':{type:[String]},
    'living conditions explanation':{type:String,required: true},
    'emergency contact first name': {type: String, required: true},
    'emergency contact last name': {type: String, required: true},
    'emergency contact street address': {type: String, required: true},
    'emergency contact zip': {type: String, required: true},
    'emergency contact phone': {type: String, required: true},
    'emergency contact email': {type: String, required: true},
    'program selection':{type:[String],required: true},
    'religious beliefs':{type:String},
    'open to prayer':{type:String,required: true},
    'Financial assistance':{type:String,required: true},
    'financial income level':{type:String},
    'financial income source':{type:String},
    'financial services needed':{type:[String]},
    'financial assistance explanation':{type:String},
    'financial healing explanation':{type:String},
    'applicant acknowledgement':{type:Boolean,required: true},
})

const singularCollectionName = 'Patient'
const Patient = mongoose.model(singularCollectionName, patientSchema);

module.exports = Patient
